---
# tasks file for roles/redis

- name: system packages | install epel repo
  become: yes
  yum:
    name: epel-release
    state: present

- name: install redis
  become: yes
  yum:
    name: redis
    state: present

- name: configure redis
  become: yes
  lineinfile:
    dest: /etc/redis.conf
    line: "bind {{ redis_listen | default('127.0.0.1') }}"
    regexp: "^bind\\s.*"
    state: present
  notify:
    - restart redis

- name: set redis to start on startup
  become: yes
  service:
    name: redis
    state: started
    enabled: yes
